"use client"
import React from "react";
import { Box } from "@mui/material";
import Grid from "@mui/material/Grid";

//layout
import ParentCardWithButtonAndSubheading from "@/app/_componets/shared/ParentCardWithButtonAndSubheading";
import XYChartLayout from "./views/XYChart";
import HeatMapLayout from "./views/HeatMap";
import RectangularTreeMapLayout from "./views/RectangularTreeMap";
import DivergentStackedBarsChartLayout from "./views/DivergentStackedBarsChart";
import PackedCirclesLayout from "./views/PackedCircles";
import PictorialStackedChartLayout from "./views/PictorialStackedChart";
//interface
const OtherGraphs = () => {
  return (
    <Box>
      <Grid container spacing={1} sx={{ padding: '10px' }}>
        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 6 }} sx={{ alignItems: 'center' }}>
          <ParentCardWithButtonAndSubheading title="XY Chart" subHeader="View the revenue generated by month">
            <XYChartLayout />
          </ParentCardWithButtonAndSubheading>
        </Grid>
        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 6 }} sx={{ alignItems: 'center' }}>
          <ParentCardWithButtonAndSubheading title="Heat Map" subHeader="View the company's performance">
            <HeatMapLayout />
          </ParentCardWithButtonAndSubheading>
        </Grid>
        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 6 }} sx={{ alignItems: 'center' }}>
          <ParentCardWithButtonAndSubheading title="Rectangular Tree Map" subHeader="View the word distribution as rectangles for a restaurant">
            <RectangularTreeMapLayout />
          </ParentCardWithButtonAndSubheading>
        </Grid>
        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 6 }} sx={{ alignItems: 'center' }}>
          <ParentCardWithButtonAndSubheading title="Divergent Stacked Bars Chart" subHeader="View the service rating at a restaurant">
            <DivergentStackedBarsChartLayout />
          </ParentCardWithButtonAndSubheading>
        </Grid>
        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 6 }} sx={{ alignItems: 'center' }}>
          <ParentCardWithButtonAndSubheading title="Packed Circles" subHeader="View the word distribution as stacked circles for a restaurant">
            <PackedCirclesLayout />
          </ParentCardWithButtonAndSubheading>
        </Grid>
        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 6 }} sx={{ alignItems: 'center' }}>
          <ParentCardWithButtonAndSubheading title="Pictorial Stacked Chart" subHeader="View the company's performance">
            <PictorialStackedChartLayout />
          </ParentCardWithButtonAndSubheading>
        </Grid>
      </Grid>
    </Box >
  );
}
export default OtherGraphs; 