import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeReactProvider } from "@/utils/themeProvider";
import { CssBaseline, useTheme } from "@mui/material";
// const theme = useTheme();
// const mode = theme.palette.mode;
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pratice Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeReactProvider>
          <CssBaseline />
          {children}
        </ThemeReactProvider>
      </body>
    </html>
  );
}
