export const sampleWords = [
  { word: "TREE", description: "A tall plant with a trunk, branches, and leaves." },
  { word: "BOOK", description: "A collection of pages with written or printed text." },
  { word: "GAME", description: "An activity played for fun or competition." },
  { word: "CODE", description: "Instructions written for computers to follow." },
  { word: "FISH", description: "An animal that lives in water and has gills." },
  { word: "STAR", description: "A bright point of light in the night sky." },
  { word: "RAIN", description: "Water droplets that fall from clouds." },
  { word: "LOVE", description: "A strong feeling of affection and care." },
  { word: "FROG", description: "A small green animal that hops and croaks." },
  { word: "MOON", description: "The round object that orbits the Earth." },
  { word: "WIND", description: "Moving air felt as a breeze or gust." },
  { word: "SNOW", description: "Frozen white flakes that fall in winter." },
  { word: "SUN", description: "The star at the center of our solar system." },
  { word: "DOG", description: "A loyal animal often kept as a pet." },
  { word: "CAT", description: "A small furry animal that purrs and meows." },
  { word: "BIRD", description: "An animal with wings that can often fly." },
  { word: "LION", description: "A big wild cat known as the king of the jungle." },
  { word: "WOLF", description: "A wild dog that howls at night." },
  { word: "BEAR", description: "A large strong animal that lives in forests." },
  { word: "SHIP", description: "A big boat that sails on water." },
  { word: "CAR", description: "A vehicle with four wheels used for travel." },
  { word: "BIKE", description: "A two-wheeled vehicle you can ride." },
  { word: "ROAD", description: "A path for vehicles and people to travel." },
  { word: "MAP", description: "A drawing that shows locations and places." },
  { word: "KEY", description: "A small tool used to open locks." },
  { word: "LOCK", description: "A device that keeps things closed or safe." },
  { word: "DOOR", description: "A movable barrier at the entrance of a place." },
  { word: "WALL", description: "A structure that divides or surrounds an area." },
  { word: "ROOM", description: "A space inside a building." },
  { word: "BED", description: "Furniture used for sleeping." },
  { word: "FOOD", description: "Something people and animals eat." },
  { word: "CAKE", description: "A sweet dessert often eaten at parties." },
  { word: "MILK", description: "A white drink from cows, goats, or almonds." },
  { word: "EGGS", description: "Oval food laid by chickens." },
  { word: "RICE", description: "Small white grains eaten with meals." },
  { word: "BEAN", description: "A small seed eaten as food." },
  { word: "SALT", description: "A white seasoning that makes food tasty." },
  { word: "TEA", description: "A hot drink made from leaves." },
  { word: "JAVA", description: "A slang name for coffee, also a coding language." },
  { word: "MATH", description: "The study of numbers and shapes." },
  { word: "TIME", description: "A way to measure hours, minutes, and seconds." },
  { word: "YEAR", description: "A period of 12 months." },
  { word: "DAY", description: "A period of 24 hours." },
  { word: "NIGHT", description: "The dark time when the sun is gone." },
  { word: "FIRE", description: "Flames that give heat and light." },
  { word: "WATER", description: "A clear liquid needed for life." },
  { word: "ICE", description: "Frozen water, cold and solid." },
  { word: "ROCK", description: "A hard natural stone." },
  { word: "GOLD", description: "A shiny yellow valuable metal." },
];