import * as am5 from "@amcharts/amcharts5";

export interface circleTemplateType { fill: am5.Color; }
export interface polygonSettingsType { disabled: boolean, active: boolean, tooltipHTML: string, toggleKey: string, interactive: boolean, fill: am5.Color; }
export interface motionChartDataType { id: string | number; name: string; continent: string; settings: { fill: am5.Color }; x: number; y: number; value: number; }
export interface countryType { name: string; continent: string; data?: Array<motionChartDataType> | undefined; }
export interface dataType {
  id: string;
  name: string;
  value: number;
  review_rating:
  number;
  nps: number;
  sentiment: string;
  cursor: string;
  circleTemp?: circleTemplateType;
  polygonSettings?: polygonSettingsType;
  countyValueGroup?: string;
}

export const bubbleMapData: dataType[] = [
  { id: "US", name: "United States", value: 500, review_rating: 4.3, nps: 62, sentiment: "Positive", cursor: "pointer" },
  { id: "CA", name: "Canada", value: 220, review_rating: 4.1, nps: 55, sentiment: "Positive", cursor: "pointer" },
  { id: "BR", name: "Brazil", value: 180, review_rating: 3.9, nps: 40, sentiment: "Neutral", cursor: "pointer" },
  { id: "MX", name: "Mexico", value: 8, review_rating: 3.7, nps: 35, sentiment: "Neutral", cursor: "pointer" },
  { id: "AR", name: "Argentina", value: 95, review_rating: 3.8, nps: 38, sentiment: "Neutral", cursor: "pointer" },
  { id: "GB", name: "United Kingdom", value: 300, review_rating: 4.2, nps: 58, sentiment: "Positive", cursor: "pointer" },
  { id: "FR", name: "France", value: 30, review_rating: 4.0, nps: 50, sentiment: "Positive", cursor: "pointer" },
  { id: "DE", name: "Germany", value: 24, review_rating: 4.4, nps: 65, sentiment: "Positive", cursor: "pointer" },
  { id: "ES", name: "Spain", value: 210, review_rating: 4.1, nps: 52, sentiment: "Positive", cursor: "pointer" },
  { id: "IT", name: "Italy", value: 2, review_rating: 4.0, nps: 48, sentiment: "Neutral", cursor: "pointer" },
  { id: "CN", name: "China", value: 400, review_rating: 3.6, nps: 30, sentiment: "Neutral", cursor: "pointer" },
  { id: "JP", name: "Japan", value: 320, review_rating: 4.3, nps: 60, sentiment: "Positive", cursor: "pointer" },
  { id: "IN", name: "India", value: 14, review_rating: 3.9, nps: 42, sentiment: "Neutral", cursor: "pointer" },
  { id: "KR", name: "South Korea", value: 190, review_rating: 4.2, nps: 53, sentiment: "Positive", cursor: "pointer" },
  { id: "SG", name: "Singapore", value: 85, review_rating: 4.5, nps: 70, sentiment: "Positive", cursor: "pointer" },
  { id: "AU", name: "Australia", value: 2, review_rating: 4.1, nps: 54, sentiment: "Positive", cursor: "pointer" },
  { id: "NZ", name: "New Zealand", value: 75, review_rating: 4.6, nps: 72, sentiment: "Positive", cursor: "pointer" },
  { id: "ZA", name: "South Africa", value: 150, review_rating: 3.7, nps: 36, sentiment: "Neutral", cursor: "pointer" },
  { id: "NG", name: "Nigeria", value: 8, review_rating: 3.5, nps: 28, sentiment: "Negative", cursor: "pointer" },
  { id: "EG", name: "Egypt", value: 30, review_rating: 3.8, nps: 34, sentiment: "Neutral", cursor: "pointer" },
  { id: "RU", name: "Russia", value: 260, review_rating: 3.6, nps: 32, sentiment: "Neutral", cursor: "pointer" },
  { id: "TR", name: "Turkey", value: 170, review_rating: 3.9, nps: 41, sentiment: "Neutral", cursor: "pointer" },
  { id: "SA", name: "Saudi Arabia", value: 140, review_rating: 3.7, nps: 37, sentiment: "Neutral", cursor: "pointer" },
  { id: "AE", name: "United Arab Emirates", value: 3, review_rating: 4.2, nps: 56, sentiment: "Positive", cursor: "pointer" },
  { id: "IL", name: "Israel", value: 90, review_rating: 4.0, nps: 45, sentiment: "Positive", cursor: "pointer" },
];

export const PolygonMapData: dataType[] = [
  { id: "US", name: "United States", value: 500, review_rating: 4.3, nps: 62, sentiment: "Positive", cursor: "pointer" },
  { id: "CA", name: "Canada", value: 220, review_rating: 4.1, nps: 55, sentiment: "Positive", cursor: "pointer" },
  { id: "BR", name: "Brazil", value: 180, review_rating: 3.9, nps: 40, sentiment: "Neutral", cursor: "pointer" },
  { id: "MX", name: "Mexico", value: 8, review_rating: 3.7, nps: 35, sentiment: "Neutral", cursor: "pointer" },
  { id: "AR", name: "Argentina", value: 95, review_rating: 3.8, nps: 38, sentiment: "Neutral", cursor: "pointer" },
  { id: "GB", name: "United Kingdom", value: 300, review_rating: 4.2, nps: 58, sentiment: "Positive", cursor: "pointer" },
  { id: "FR", name: "France", value: 30, review_rating: 4.0, nps: 50, sentiment: "Positive", cursor: "pointer" },
  { id: "DE", name: "Germany", value: 24, review_rating: 4.4, nps: 65, sentiment: "Positive", cursor: "pointer" },
  { id: "ES", name: "Spain", value: 210, review_rating: 4.1, nps: 52, sentiment: "Positive", cursor: "pointer" },
  { id: "IT", name: "Italy", value: 2, review_rating: 4.0, nps: 48, sentiment: "Neutral", cursor: "pointer" },
  { id: "CN", name: "China", value: 400, review_rating: 3.6, nps: 30, sentiment: "Neutral", cursor: "pointer" },
  { id: "JP", name: "Japan", value: 320, review_rating: 4.3, nps: 60, sentiment: "Positive", cursor: "pointer" },
  { id: "IN", name: "India", value: 14, review_rating: 3.9, nps: 42, sentiment: "Neutral", cursor: "pointer" },
  { id: "KR", name: "South Korea", value: 190, review_rating: 4.2, nps: 53, sentiment: "Positive", cursor: "pointer" },
  { id: "SG", name: "Singapore", value: 85, review_rating: 4.5, nps: 70, sentiment: "Positive", cursor: "pointer" },
  { id: "AU", name: "Australia", value: 2, review_rating: 4.1, nps: 54, sentiment: "Positive", cursor: "pointer" },
  { id: "NZ", name: "New Zealand", value: 75, review_rating: 4.6, nps: 72, sentiment: "Positive", cursor: "pointer" },
  { id: "ZA", name: "South Africa", value: 150, review_rating: 3.7, nps: 36, sentiment: "Neutral", cursor: "pointer" },
  { id: "NG", name: "Nigeria", value: 8, review_rating: 3.5, nps: 28, sentiment: "Negative", cursor: "pointer" },
  { id: "EG", name: "Egypt", value: 30, review_rating: 3.8, nps: 34, sentiment: "Neutral", cursor: "pointer" },
  { id: "RU", name: "Russia", value: 260, review_rating: 3.6, nps: 32, sentiment: "Neutral", cursor: "pointer" },
  { id: "TR", name: "Turkey", value: 170, review_rating: 3.9, nps: 41, sentiment: "Neutral", cursor: "pointer" },
  { id: "SA", name: "Saudi Arabia", value: 140, review_rating: 3.7, nps: 37, sentiment: "Neutral", cursor: "pointer" },
  { id: "AE", name: "United Arab Emirates", value: 3, review_rating: 4.2, nps: 56, sentiment: "Positive", cursor: "pointer" },
  { id: "IL", name: "Israel", value: 90, review_rating: 4.0, nps: 45, sentiment: "Positive", cursor: "pointer" },
];

export let countries: Record<string, countryType> = {
  "AF": { "name": "Afghanistan", "continent": "AS" },
  "AX": { "name": "Aland Islands", "continent": "EU" },
  "AL": { "name": "Albania", "continent": "EU" },
  "DZ": { "name": "Algeria", "continent": "AF" },
  "AS": { "name": "American Samoa", "continent": "OC" },
  "AD": { "name": "Andorra", "continent": "EU" },
  "AO": { "name": "Angola", "continent": "AF" },
  "AI": { "name": "Anguilla", "continent": "NA" },
  "AQ": { "name": "Antarctica", "continent": "AN" },
  "AG": { "name": "Antigua and Barbuda", "continent": "NA" },
  "AR": { "name": "Argentina", "continent": "SA" },
  "AM": { "name": "Armenia", "continent": "AS" },
  "AW": { "name": "Aruba", "continent": "NA" },
  "AU": { "name": "Australia", "continent": "OC" },
  "AT": { "name": "Austria", "continent": "EU" },
  "AZ": { "name": "Azerbaijan", "continent": "AS" },
  "BS": { "name": "Bahamas", "continent": "NA" },
  "BH": { "name": "Bahrain", "continent": "AS" },
  "BD": { "name": "Bangladesh", "continent": "AS" },
  "BB": { "name": "Barbados", "continent": "NA" },
  "BY": { "name": "Belarus", "continent": "EU" },
  "BE": { "name": "Belgium", "continent": "EU" },
  "BZ": { "name": "Belize", "continent": "NA" },
  "BJ": { "name": "Benin", "continent": "AF" },
  "BM": { "name": "Bermuda", "continent": "NA" },
  "BT": { "name": "Bhutan", "continent": "AS" },
  "BO": { "name": "Bolivia", "continent": "SA" },
  "BQ": { "name": "Bonaire, Sint Eustatius and Saba", "continent": "NA" },
  "BA": { "name": "Bosnia and Herzegovina", "continent": "EU" },
  "BW": { "name": "Botswana", "continent": "AF" },
  "BV": { "name": "Bouvet Island", "continent": "AN" },
  "BR": { "name": "Brazil", "continent": "SA" },
  "IO": { "name": "British Indian Ocean Territory", "continent": "AS" },
  "BN": { "name": "Brunei Darussalam", "continent": "AS" },
  "BG": { "name": "Bulgaria", "continent": "EU" },
  "BF": { "name": "Burkina Faso", "continent": "AF" },
  "BI": { "name": "Burundi", "continent": "AF" },
  "KH": { "name": "Cambodia", "continent": "AS" },
  "CM": { "name": "Cameroon", "continent": "AF" },
  "CA": { "name": "Canada", "continent": "NA" },
  "CV": { "name": "Cape Verde", "continent": "AF" },
  "KY": { "name": "Cayman Islands", "continent": "NA" },
  "CF": { "name": "Central African Republic", "continent": "AF" },
  "TD": { "name": "Chad", "continent": "AF" },
  "CL": { "name": "Chile", "continent": "SA" },
  "CN": { "name": "China", "continent": "AS" },
  "CX": { "name": "Christmas Island", "continent": "AS" },
  "CC": { "name": "Cocos (Keeling) Islands", "continent": "AS" },
  "CO": { "name": "Colombia", "continent": "SA" },
  "KM": { "name": "Comoros", "continent": "AF" },
  "CG": { "name": "Congo", "continent": "AF" },
  "CD": { "name": "Congo, Democratic Republic of the Congo", "continent": "AF" },
  "CK": { "name": "Cook Islands", "continent": "OC" },
  "CR": { "name": "Costa Rica", "continent": "NA" },
  "CI": { "name": "Cote D'Ivoire", "continent": "AF" },
  "HR": { "name": "Croatia", "continent": "EU" },
  "CU": { "name": "Cuba", "continent": "NA" },
  "CW": { "name": "Curacao", "continent": "NA" },
  "CY": { "name": "Cyprus", "continent": "AS" },
  "CZ": { "name": "Czech Republic", "continent": "EU" },
  "DK": { "name": "Denmark", "continent": "EU" },
  "DJ": { "name": "Djibouti", "continent": "AF" },
  "DM": { "name": "Dominica", "continent": "NA" },
  "DO": { "name": "Dominican Republic", "continent": "NA" },
  "EC": { "name": "Ecuador", "continent": "SA" },
  "EG": { "name": "Egypt", "continent": "AF" },
  "SV": { "name": "El Salvador", "continent": "NA" },
  "GQ": { "name": "Equatorial Guinea", "continent": "AF" },
  "ER": { "name": "Eritrea", "continent": "AF" },
  "EE": { "name": "Estonia", "continent": "EU" },
  "ET": { "name": "Ethiopia", "continent": "AF" },
  "FK": { "name": "Falkland Islands (Malvinas)", "continent": "SA" },
  "FO": { "name": "Faroe Islands", "continent": "EU" },
  "FJ": { "name": "Fiji", "continent": "OC" },
  "FI": { "name": "Finland", "continent": "EU" },
  "FR": { "name": "France", "continent": "EU" },
  "GF": { "name": "French Guiana", "continent": "SA" },
  "PF": { "name": "French Polynesia", "continent": "OC" },
  "TF": { "name": "French Southern Territories", "continent": "AN" },
  "GA": { "name": "Gabon", "continent": "AF" },
  "GM": { "name": "Gambia", "continent": "AF" },
  "GE": { "name": "Georgia", "continent": "AS" },
  "DE": { "name": "Germany", "continent": "EU" },
  "GH": { "name": "Ghana", "continent": "AF" },
  "GI": { "name": "Gibraltar", "continent": "EU" },
  "GR": { "name": "Greece", "continent": "EU" },
  "GL": { "name": "Greenland", "continent": "NA" },
  "GD": { "name": "Grenada", "continent": "NA" },
  "GP": { "name": "Guadeloupe", "continent": "NA" },
  "GU": { "name": "Guam", "continent": "OC" },
  "GT": { "name": "Guatemala", "continent": "NA" },
  "GG": { "name": "Guernsey", "continent": "EU" },
  "GN": { "name": "Guinea", "continent": "AF" },
  "GW": { "name": "Guinea-Bissau", "continent": "AF" },
  "GY": { "name": "Guyana", "continent": "SA" },
  "HT": { "name": "Haiti", "continent": "NA" },
  "HM": { "name": "Heard Island and Mcdonald Islands", "continent": "AN" },
  "VA": { "name": "Holy See (Vatican City State)", "continent": "EU" },
  "HN": { "name": "Honduras", "continent": "NA" },
  "HK": { "name": "Hong Kong", "continent": "AS" },
  "HU": { "name": "Hungary", "continent": "EU" },
  "IS": { "name": "Iceland", "continent": "EU" },
  "IN": { "name": "India", "continent": "AS" },
  "ID": { "name": "Indonesia", "continent": "AS" },
  "IR": { "name": "Iran, Islamic Republic of", "continent": "AS" },
  "IQ": { "name": "Iraq", "continent": "AS" },
  "IE": { "name": "Ireland", "continent": "EU" },
  "IM": { "name": "Isle of Man", "continent": "EU" },
  "IL": { "name": "Israel", "continent": "AS" },
  "IT": { "name": "Italy", "continent": "EU" },
  "JM": { "name": "Jamaica", "continent": "NA" },
  "JP": { "name": "Japan", "continent": "AS" },
  "JE": { "name": "Jersey", "continent": "EU" },
  "JO": { "name": "Jordan", "continent": "AS" },
  "KZ": { "name": "Kazakhstan", "continent": "AS" },
  "KE": { "name": "Kenya", "continent": "AF" },
  "KI": { "name": "Kiribati", "continent": "OC" },
  "KP": { "name": "Korea, Democratic People's Republic of", "continent": "AS" },
  "KR": { "name": "Korea, Republic of", "continent": "AS" },
  "XK": { "name": "Kosovo", "continent": "EU" },
  "KW": { "name": "Kuwait", "continent": "AS" },
  "KG": { "name": "Kyrgyzstan", "continent": "AS" },
  "LA": { "name": "Lao People's Democratic Republic", "continent": "AS" },
  "LV": { "name": "Latvia", "continent": "EU" },
  "LB": { "name": "Lebanon", "continent": "AS" },
  "LS": { "name": "Lesotho", "continent": "AF" },
  "LR": { "name": "Liberia", "continent": "AF" },
  "LY": { "name": "Libyan Arab Jamahiriya", "continent": "AF" },
  "LI": { "name": "Liechtenstein", "continent": "EU" },
  "LT": { "name": "Lithuania", "continent": "EU" },
  "LU": { "name": "Luxembourg", "continent": "EU" },
  "MO": { "name": "Macao", "continent": "AS" },
  "MK": { "name": "Macedonia, the Former Yugoslav Republic of", "continent": "EU" },
  "MG": { "name": "Madagascar", "continent": "AF" },
  "MW": { "name": "Malawi", "continent": "AF" },
  "MY": { "name": "Malaysia", "continent": "AS" },
  "MV": { "name": "Maldives", "continent": "AS" },
  "ML": { "name": "Mali", "continent": "AF" },
  "MT": { "name": "Malta", "continent": "EU" },
  "MH": { "name": "Marshall Islands", "continent": "OC" },
  "MQ": { "name": "Martinique", "continent": "NA" },
  "MR": { "name": "Mauritania", "continent": "AF" },
  "MU": { "name": "Mauritius", "continent": "AF" },
  "YT": { "name": "Mayotte", "continent": "AF" },
  "MX": { "name": "Mexico", "continent": "NA" },
  "FM": { "name": "Micronesia, Federated States of", "continent": "OC" },
  "MD": { "name": "Moldova, Republic of", "continent": "EU" },
  "MC": { "name": "Monaco", "continent": "EU" },
  "MN": { "name": "Mongolia", "continent": "AS" },
  "ME": { "name": "Montenegro", "continent": "EU" },
  "MS": { "name": "Montserrat", "continent": "NA" },
  "MA": { "name": "Morocco", "continent": "AF" },
  "MZ": { "name": "Mozambique", "continent": "AF" },
  "MM": { "name": "Myanmar", "continent": "AS" },
  "NA": { "name": "Namibia", "continent": "AF" },
  "NR": { "name": "Nauru", "continent": "OC" },
  "NP": { "name": "Nepal", "continent": "AS" },
  "NL": { "name": "Netherlands", "continent": "EU" },
  "AN": { "name": "Netherlands Antilles", "continent": "NA" },
  "NC": { "name": "New Caledonia", "continent": "OC" },
  "NZ": { "name": "New Zealand", "continent": "OC" },
  "NI": { "name": "Nicaragua", "continent": "NA" },
  "NE": { "name": "Niger", "continent": "AF" },
  "NG": { "name": "Nigeria", "continent": "AF" },
  "NU": { "name": "Niue", "continent": "OC" },
  "NF": { "name": "Norfolk Island", "continent": "OC" },
  "MP": { "name": "Northern Mariana Islands", "continent": "OC" },
  "NO": { "name": "Norway", "continent": "EU" },
  "OM": { "name": "Oman", "continent": "AS" },
  "PK": { "name": "Pakistan", "continent": "AS" },
  "PW": { "name": "Palau", "continent": "OC" },
  "PS": { "name": "Palestinian Territory, Occupied", "continent": "AS" },
  "PA": { "name": "Panama", "continent": "NA" },
  "PG": { "name": "Papua New Guinea", "continent": "OC" },
  "PY": { "name": "Paraguay", "continent": "SA" },
  "PE": { "name": "Peru", "continent": "SA" },
  "PH": { "name": "Philippines", "continent": "AS" },
  "PN": { "name": "Pitcairn", "continent": "OC" },
  "PL": { "name": "Poland", "continent": "EU" },
  "PT": { "name": "Portugal", "continent": "EU" },
  "PR": { "name": "Puerto Rico", "continent": "NA" },
  "QA": { "name": "Qatar", "continent": "AS" },
  "RE": { "name": "Reunion", "continent": "AF" },
  "RO": { "name": "Romania", "continent": "EU" },
  "RU": { "name": "Russian Federation", "continent": "AS" },
  "RW": { "name": "Rwanda", "continent": "AF" },
  "BL": { "name": "Saint Barthelemy", "continent": "NA" },
  "SH": { "name": "Saint Helena", "continent": "AF" },
  "KN": { "name": "Saint Kitts and Nevis", "continent": "NA" },
  "LC": { "name": "Saint Lucia", "continent": "NA" },
  "MF": { "name": "Saint Martin", "continent": "NA" },
  "PM": { "name": "Saint Pierre and Miquelon", "continent": "NA" },
  "VC": { "name": "Saint Vincent and the Grenadines", "continent": "NA" },
  "WS": { "name": "Samoa", "continent": "OC" },
  "SM": { "name": "San Marino", "continent": "EU" },
  "ST": { "name": "Sao Tome and Principe", "continent": "AF" },
  "SA": { "name": "Saudi Arabia", "continent": "AS" },
  "SN": { "name": "Senegal", "continent": "AF" },
  "RS": { "name": "Serbia", "continent": "EU" },
  "CS": { "name": "Serbia and Montenegro", "continent": "EU" },
  "SC": { "name": "Seychelles", "continent": "AF" },
  "SL": { "name": "Sierra Leone", "continent": "AF" },
  "SG": { "name": "Singapore", "continent": "AS" },
  "SX": { "name": "Sint Maarten", "continent": "NA" },
  "SK": { "name": "Slovakia", "continent": "EU" },
  "SI": { "name": "Slovenia", "continent": "EU" },
  "SB": { "name": "Solomon Islands", "continent": "OC" },
  "SO": { "name": "Somalia", "continent": "AF" },
  "ZA": { "name": "South Africa", "continent": "AF" },
  "GS": { "name": "South Georgia and the South Sandwich Islands", "continent": "AN" },
  "SS": { "name": "South Sudan", "continent": "AF" },
  "ES": { "name": "Spain", "continent": "EU" },
  "LK": { "name": "Sri Lanka", "continent": "AS" },
  "SD": { "name": "Sudan", "continent": "AF" },
  "SR": { "name": "Suriname", "continent": "SA" },
  "SJ": { "name": "Svalbard and Jan Mayen", "continent": "EU" },
  "SZ": { "name": "Swaziland", "continent": "AF" },
  "SE": { "name": "Sweden", "continent": "EU" },
  "CH": { "name": "Switzerland", "continent": "EU" },
  "SY": { "name": "Syrian Arab Republic", "continent": "AS" },
  "TW": { "name": "Taiwan, Province of China", "continent": "AS" },
  "TJ": { "name": "Tajikistan", "continent": "AS" },
  "TZ": { "name": "Tanzania, United Republic of", "continent": "AF" },
  "TH": { "name": "Thailand", "continent": "AS" },
  "TL": { "name": "Timor-Leste", "continent": "AS" },
  "TG": { "name": "Togo", "continent": "AF" },
  "TK": { "name": "Tokelau", "continent": "OC" },
  "TO": { "name": "Tonga", "continent": "OC" },
  "TT": { "name": "Trinidad and Tobago", "continent": "NA" },
  "TN": { "name": "Tunisia", "continent": "AF" },
  "TR": { "name": "Turkey", "continent": "AS" },
  "TM": { "name": "Turkmenistan", "continent": "AS" },
  "TC": { "name": "Turks and Caicos Islands", "continent": "NA" },
  "TV": { "name": "Tuvalu", "continent": "OC" },
  "UG": { "name": "Uganda", "continent": "AF" },
  "UA": { "name": "Ukraine", "continent": "EU" },
  "AE": { "name": "United Arab Emirates", "continent": "AS" },
  "GB": { "name": "United Kingdom", "continent": "EU" },
  "US": { "name": "United States", "continent": "NA" },
  "UM": { "name": "United States Minor Outlying Islands", "continent": "NA" },
  "UY": { "name": "Uruguay", "continent": "SA" },
  "UZ": { "name": "Uzbekistan", "continent": "AS" },
  "VU": { "name": "Vanuatu", "continent": "OC" },
  "VE": { "name": "Venezuela", "continent": "SA" },
  "VN": { "name": "Viet Nam", "continent": "AS" },
  "VG": { "name": "Virgin Islands, British", "continent": "NA" },
  "VI": { "name": "Virgin Islands, U.s.", "continent": "NA" },
  "WF": { "name": "Wallis and Futuna", "continent": "OC" },
  "EH": { "name": "Western Sahara", "continent": "AF" },
  "YE": { "name": "Yemen", "continent": "AS" },
  "ZM": { "name": "Zambia", "continent": "AF" },
  "ZW": { "name": "Zimbabwe", "continent": "AF" }
};