export interface WordCloudDataType { text: string; value: number; sentiment: string; polarities: string; color: string; }
export const movieGenresWordCloud: WordCloudDataType[] = [
    { text: "Action", value: 50, sentiment: "positive", polarities: "high", color: "#E53935" },
    { text: "Adventure", value: 42, sentiment: "positive", polarities: "medium", color: "#FB8C00" },
    { text: "Comedy", value: 45, sentiment: "positive", polarities: "medium", color: "#FFB300" },
    { text: "Romantic Comedy", value: 28, sentiment: "positive", polarities: "low", color: "#F06292" },
    { text: "Drama", value: 40, sentiment: "neutral", polarities: "medium", color: "#8E24AA" },
    { text: "Historical Drama", value: 25, sentiment: "neutral", polarities: "low", color: "#AB47BC" },
    { text: "Horror", value: 30, sentiment: "negative", polarities: "high", color: "#3949AB" },
    { text: "Psychological Horror", value: 20, sentiment: "negative", polarities: "high", color: "#1A237E" },
    { text: "Romance", value: 35, sentiment: "positive", polarities: "low", color: "#D81B60" },
    { text: "Sci-Fi", value: 38, sentiment: "positive", polarities: "high", color: "#00ACC1" },
    { text: "Cyberpunk", value: 18, sentiment: "neutral", polarities: "medium", color: "#00897B" },
    { text: "Fantasy", value: 36, sentiment: "neutral", polarities: "medium", color: "#43A047" },
    { text: "Epic Fantasy", value: 22, sentiment: "positive", polarities: "medium", color: "#2E7D32" },
    { text: "Thriller", value: 32, sentiment: "negative", polarities: "high", color: "#F4511E" },
    { text: "Crime Thriller", value: 27, sentiment: "negative", polarities: "high", color: "#BF360C" },
    { text: "Documentary", value: 24, sentiment: "neutral", polarities: "low", color: "#6D4C41" },
    { text: "Biographical", value: 20, sentiment: "neutral", polarities: "medium", color: "#5D4037" },
    { text: "Animation", value: 34, sentiment: "positive", polarities: "medium", color: "#7CB342" },
    { text: "Family", value: 30, sentiment: "positive", polarities: "low", color: "#C0CA33" },
    { text: "Musical", value: 26, sentiment: "positive", polarities: "medium", color: "#FF7043" },
    { text: "War", value: 19, sentiment: "neutral", polarities: "high", color: "#8D6E63" },
    { text: "Western", value: 21, sentiment: "neutral", polarities: "medium", color: "#A1887F" },
    { text: "Mystery", value: 29, sentiment: "neutral", polarities: "medium", color: "#3949AB" },
    { text: "Sports", value: 23, sentiment: "positive", polarities: "low", color: "#1E88E5" },
    { text: "Superhero", value: 37, sentiment: "positive", polarities: "high", color: "#1976D2" },
];

export interface sentenceCloudDataType { category: string; value: number; color: string; }
export const reviewsData: sentenceCloudDataType[] = [
    { category: "The room was spacious and clean, but the view was average", value: 4.1, color: "#7ec991" },
    { category: "The service was slow and unresponsive, disappointing experience", value: 2.3, color: "#e55d5d" },
    { category: "Breakfast was included but it was just okay", value: 3.0, color: "#c9c9cd" },
    { category: "Loved the location, close to the city center", value: 4.5, color: "#7ec991" },
    { category: "Uncomfortable beds and noisy at night, poor sleep quality", value: 1.8, color: "#e55d5d" },
    { category: "Average stay, but the staff were helpful", value: 3.2, color: "#c9c9cd" },
    { category: "The pool was fantastic and well-maintained", value: 4.7, color: "#7ec991" },
    { category: "Room was small and smelled of damp", value: 2.0, color: "#e55d5d" },
    { category: "Convenient location, but the parking was limited", value: 3.3, color: "#c9c9cd" },
    { category: "The food at the restaurant was delicious!", value: 4.8, color: "#7ec991" },
    { category: "Terrible Wi-Fi connection, couldn't work properly", value: 1.9, color: "#e55d5d" },
    { category: "Nice atmosphere, though the room decor felt outdated", value: 3.5, color: "#c9c9cd" },
    { category: "Cleanliness and hospitality were top-notch", value: 4.6, color: "#7ec991" },
    { category: "The shower was difficult to use, and the water pressure was low", value: 2.4, color: "#e55d5d" },
    { category: "Good for the price, but don't expect luxury", value: 3.4, color: "#c9c9cd" },
    { category: "The staff went above and beyond to help us", value: 4.9, color: "#7ec991" },
    { category: "The air conditioning wasn't working properly", value: 2.1, color: "#e55d5d" },
    { category: "Had an average stay, no major issues", value: 3.0, color: "#c9c9cd" },
    { category: "The view from the balcony was breathtaking", value: 4.8, color: "#7ec991" },
    { category: "The walls were thin, I could hear my neighbors", value: 2.2, color: "#e55d5d" }
];